# Generated by Django 2.0.2 on 2018-02-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='placefeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='placefeature',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placephonenumber',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='place',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='place',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='PlaceFeature',
        ),
        migrations.DeleteModel(
            name='PlacePhoneNumber',
        ),
        migrations.DeleteModel(
            name='PlacePhoto',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
