# Generated by Django 2.0.2 on 2018-02-08 21:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_auto_20180208_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('icon', models.ImageField(upload_to='media/uploads/category_icons/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='City Name')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='media/uploads/features_icons/')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Place')),
                ('web_site_link', models.CharField(default='null', max_length=200, null=True, verbose_name='Web-Site')),
                ('address', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(default=0, verbose_name='Latitude')),
                ('lng', models.FloatField(default=0, verbose_name='Longitude')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='PlaceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Feature')),
            ],
            options={
                'verbose_name': 'Place Features',
                'verbose_name_plural': 'Place Features',
            },
        ),
        migrations.CreateModel(
            name='PlacePhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Phone Numbers of Place',
                'verbose_name_plural': 'Phone Numbers of Place',
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.Place')),
                ('opens_on_mondays', models.TimeField(blank=True, null=True)),
                ('opens_on_tuesdays', models.TimeField(blank=True, null=True)),
                ('opens_on_wednesdays', models.TimeField(blank=True, null=True)),
                ('opens_on_thursdays', models.TimeField(blank=True, null=True)),
                ('opens_on_fridays', models.TimeField(blank=True, null=True)),
                ('opens_on_saturdays', models.TimeField(blank=True, null=True)),
                ('opens_on_sundays', models.TimeField(blank=True, null=True)),
                ('closes_on_mondays', models.TimeField(blank=True, null=True)),
                ('closes_on_tuesdays', models.TimeField(blank=True, null=True)),
                ('closes_on_wednesdays', models.TimeField(blank=True, null=True)),
                ('closes_on_thursdays', models.TimeField(blank=True, null=True)),
                ('closes_on_fridays', models.TimeField(blank=True, null=True)),
                ('closes_on_saturdays', models.TimeField(blank=True, null=True)),
                ('closes_on_sundays', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AddField(
            model_name='placephoto',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='placephonenumber',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='placefeature',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.City'),
        ),
        migrations.AddField(
            model_name='place',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.SubCategory'),
        ),
    ]
